### ISSUE TITLE
Label information

### ISSUE THREAD

**Issue by willxxy** [JeremyNixon/neurosity#1]
Hello,

Thank you for the great work and publicly releasing the dataset. 
I was wondering in your transformer training pipeline file `train_transformer.py,` what the labels represent. 
I was assuming given a time series amplitude of length T, the label is the next T+1 amplitude. Is this a correct assumption?

Thank you,
William Han

**Comment by JeremyNixon** [comment]
Yes, they're the T+1 amplitude.

They're constructed on lines 35-44:
for i in range(len(session_df) - 33):
    datapoint = session_df[i:32+i].to_numpy()
    label = session_df.iloc[32+i+1].to_numpy()

    if i < split_point:
        training_datapoints.append(datapoint)
        training_labels.append(label)
    else:
        validation_datapoints.append(datapoint)
        validation_labels.append(label)


As you can see, the training input is 32 previous timesteps, and the label
is the next timestep.

**Comment by willxxy** [comment]
Okay! Thank you for the quick clarification.
